### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Indigrep** [RolandDreger/indesign-word-import#2]
Hello Roland
I tested the script with two Word files (330 and 230 pages, tables, notes, revisions). Both files are correctly formatted with character and paragraph styles. Comparing the Word and the InDesign, here is what I noticed: 

1. Character styles 

- Spaces and special characters  (+, underscore) are deleted in name

- The specificities of the styles disappear

- Styles disappeared even though they are in the Word 

- Styles are replaced by new ones (ex. : [Sans] by lang-val_it-IT ; Italic by lang-val_it-IT Italic). A lot of new styles are created

1. Paragraph styles

-  Spaces and special characters  (+, underscore) are deleted in name
- The language has changed from French to English
- Normal style became Standard

1. Others

- Sectionbreaks have been placed in the text in the middle of a sentence
If you want, I can send you documents (word and InDesign CC21)
Best
Laurent

**Comment by RolandDreger** [comment]
Hello Laurent,

thank you for your feedback. Yes, please send me the files. I'll take a look at them and then reply specifically to the individual points.

Just basically, I need to write that in more detail in the readme file: No style *properties* are taken over from Word only the style names and their assignment to the text places. The format properties must be set in InDesign. That is a feature not a bug 🙂

Best regards
Roland

**Comment by Indigrep** [comment]
Hello Roland
Here are three documents:
1) Original_InDesign: in my workflow (for the dialogue with authors), I import the Word file and format it (I apply character and paragraph styles). Then I export it to Word with Wordflow
2) Word: the Word file exported with Wordflow
3) ImportDocx: the document imported with ImportDocx. You will find some annotations
Best
Laurent
[Documents.zip](https://github.com/RolandDreger/indesign-word-import/files/8933569/Documents.zip)

**Comment by Indigrep** [comment]
Are you sur for the format properties ? If I import the Word in a new document, without styles in InDesign, character styles are imported too with their properties

**Comment by RolandDreger** [comment]
Thanks, I will take a look in the next few days. 

> Are you sur for the format properties ? If I import the Word in a new document, without styles in InDesign, character styles are imported too with their properties

When importing via script, the character styles are there but without properties. Maybe my bad English is causing confusion, here are two screenshots:

Word
<img width="1242" alt="Bildschirmfoto 2022-06-18 um 15 15 05" src="https://user-images.githubusercontent.com/19747449/174439780-a886fd96-7d3d-4894-8e47-af376ecf18d7.png">

InDesign
<img width="1474" alt="Bildschirmfoto 2022-06-18 um 15 19 45" src="https://user-images.githubusercontent.com/19747449/174439800-083f406a-356c-4d5a-82fa-9613e01739ac.png">

**Comment by RolandDreger** [comment]
Today I took a closer look at the mentioned issues.

> 1. Character styles
> - Spaces and special characters (+, underscore) are deleted in name

This should work better now. #5 

A bit tricky are the default styles of Word. Here language specific names are displayed in Word, but in the document English names are stored. But here alias names can be assigned: Enter a semicolon or comma after the default name and then the desired name. Alias names get the priority when importing with the script.

<img width="640" alt="alias_style_name" src="https://user-images.githubusercontent.com/19747449/174901838-3822490d-8901-416a-8e2e-549420a7586a.png">


> Styles disappeared even though they are in the Word

The properties of the character style "Super" or "Scaps" must be set in InDesgin. (As mentioned, this is a intentional design decision for the script.)


> Styles are replaced by new ones (ex. : [Sans] by lang-val_it-IT ; Italic by lang-val_it-IT Italic). A lot of new styles are created

Word applies its own character style when it thinks it recognizes a foreign language and the option is selected. Sometimes this is intentional, sometimes not. 

When importing, you have to decide whether to take over all these styles or to leave some out. There is a setting for this in the transformation, but it is not yet available in the script. I have to think about the best way to handle this.

»Italic by lang-val_it-IT Italic« means there is a character style "italic" assigned and Word also applies a character style for the language on top of it.

<img width="1312" alt="character_style_italic_and_language" src="https://user-images.githubusercontent.com/19747449/174902329-77a83093-703b-428f-a689-09dd4e61beda.png">

So unfortunately a little extra work has to be done here: Evaluate if an extra character style "lang-val_en_US Sacps" is useful, if not delete and replace it with "Sacps". 


> 2. Paragraph styles
> - Spaces and special characters (+, underscore) are deleted in name

(as with the character styles, see above)


> The language has changed from French to English

The setting for the language must be made in the specific paragraph style in InDesign.


> Normal style became Standard

This is the German name of the default style. I have to make that configurable. 


> 3. Others
> - Sectionbreaks have been placed in the text in the middle of a sentence

I'll have to take a closer look at that. The positions don't seem to fit in Word nor in InDesign. However, these XML elements are not yet used for any InDesign functionality. This is on the ToDo list.

**Comment by RolandDreger** [comment]
Hope everything works as expected now. If not, please feel free to report a new issue.
